# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Stu Mason's Overly Enthusiastic Remblings
email: stu@stuartmason.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Overly Enthusiastic ramblings of a full stack (lol) php developer based in
  LDN (London). Read my stuff. Tweet with me witty retorts or tell me what 
  is wrong in my posts (probs be quicker to tell me what is right).
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.stuartmason.co.uk" # the base hostname & protocol for your site
twitter_username: masonator
github_username:  mason8r

# Build settings
markdown: kramdown
